# Generated by Django 3.1 on 2021-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('M-pesa', 'M-pesa'), ('Paypil', 'Paypal')], default='Cash On Delivery', max_length=20),
        ),
    ]
